version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    volumes:
      - ./credentials:/app/credentials
      - ./data:/app/data
    depends_on: []

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
    environment:
      - BACKEND_URL=http://backend:5000
    depends_on:
      - backend