[build]
builder = "dockerfile"

[deploy]
startCommand = "/bin/bash -lc 'gunicorn --bind 0.0.0.0:${PORT:-5000} --workers 1 --threads 2 --timeout 30 --keep-alive 2 --log-level info --access-logfile - --error-logfile - app:app'"
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE"